---
title: "Notes_TheDataScientistsToolbox"
author: "Giacomo Zacchia"
date: '2022-12-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Purpose

This is a document for keeping notes for the John Hopkin's Class - The Data Scientist's Toolbox. I am skipping the first two weeks of information for now.

## Week 3 - Version Control

### Section 1 - Version Control Notes

GIT is the most commonly used version control system. GitHub is the website. Repository is the master file. They are hosted on GitHub. Commit is the "save" function -- you typically add notes about what you changed. Push is where you send your edits. Pull is where you sync changes that others have made. Staging is the act of just sharing one change. Clone is a copy. Fork is a copy for personal copy.

Best practices:
- Purposeful, single issue commits
- Informative commit messages
- Pull and push often

### Section 2 - Github and Git

Sign up for GitHub.
Install Git.
Link Git & GitHub.

### Section 3 - Github & RStudio

This document is now linked to Github.

## Week 4 

### Section 1 - RMarkdown

[RMarkdown Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)

### Section 2 - Types 

Types of Data Analysis (in order of difficulty)
1) Descriptive - describing set of data
2) Exploratory - Find relationships in data. Helps form hypotheses
3) Inferential - Small data to say something about the population at large
4) Predictive - Use current data to make predictions about future data
5) Causal - see what happens to one variable when we manipulate another variable
6) Mechanistic - understand the exact changes in variables that lead to exact changes in other variables

### Section 3 - Experimental Design
Formulate your question -> design experiment -> identify problems & source of error -> collect the data

retractionwatch.com

Independent variable - what we change (x-axis)
Dependent varaible - what we don't change (y-axis)

Confound are variables that may be the real cause

Control Group - a group that is not subject to change.

Randomized - randomly assign 

Replicates - repeating an experiment with new sets of data

P-Value - probability that your results are just as a result of chance
